[package]
license = ["Apache-2.0"]
keywords = ["Communication/Team Chat", "Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.google.sheets"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.5.0"
distribution = "slbeta4"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
